### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by Element118** [KhanCommunityBot/Main-files#2]
Are we going to use these files as a library? Is a refactoring processing going on? What is the current state of the workflow? Let's use issues here to track things.

**Comment by JettBurns14** [comment]
These files are borrowed directly from Khan Academy and have been translated to some extent. What we're after is code involving the "low-quality-score" system and its algorithm. We plan to add more conditions of our own so the system returns more info and covers more discussion. But before that, we need the algorithms behind the system.
